# The sample names that you want to give them
names: ['LARRY1', 'LARRY2']
# The name of the samples coming from the sequencer. The pipeline expects that there are two files for each sample ending with _R1_001.fastq.gz and _R2_001.fastq.gz 
samples:
 LARRY1: ''
 LARRY2: ''
# The cellular barcodes get this added to make them unique across samples
barcode_extension:
 LARRY1: 'lung'
 LARRY2: 'myelym'
# The path to the raw sequening data
path: ''
# Has to be in .fa format
ref_genome: ''
# The path to the panel file in BED format
panel_bed: 'infos/panel.bed'
# The path to the panel file in tsv format. There need to be one column called DropoutUncutLKs containing 1-the dropout
ampli_file: 'infos/panel.tsv'
# The number of control amplicons required to achieve a sufficient performance (the higher the more stringent)
cellfinder_cutoff: 0.7
read_length: 100
larry_version: v2
# Cutoffs for filtering and merging LARRY barcodes
nreads_larry: 5
hamming_larry: 3
batch: 'november'
